#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH=$PATH:$HOME/bin
export MANWIDTH=999
export PATH=$HOME/.fnm:$PATH
#export PATH="$PATH:./node_modules/.bin"
#eval "$(fnm env)"
#eval "$(zoxide init zsh)"

#gpp-mono
export NPM_TOKEN="02ef508c-f7ad-459f-92f0-87ec795d8014"
#go
export PATH=$PATH:/usr/local/go/bin
export GOPATH=~/projects/go
export PATH=$HOME/.local/share/go/bin:$PATH
